# For the benefit of emacs users: -*- shell-script -*-
alias ls='ls -G'
alias grep='grep --color=auto'
alias ll='ls -lG'
alias la='ls -AG'
alias lla='ls -lAG'
alias tmux='tmux -2'
alias e='emacsclient -n'
alias bazel='nocorrect bazel'
alias start-wildfly='JAVA_OPTS="-server -Xmx2G -agentlib:jdwp=transport=dt_socket,address=59496,suspend=n,server=y" /opt/jboss/bin/standalone.sh --server-config=standalone-full.xml'
alias code='"/Applications/Visual Studio Code.app//Contents/Resources/app/bin/code"'
