# For the benefit of emacs users: -*- shell-script -*-
alias ls='ls -G'
alias grep='grep --color=auto'
alias ll='ls -lG'
alias la='ls -AG'
alias lla='ls -lAG'
alias tmux='tmux -2'
alias e='emacsclient -n'
alias bazel='nocorrect bazel'
alias sc-asg='nocorrect sc-asg'
alias ssh='sc-ssh-wrapper'
