---
~/:
  name: Andrew Johnson
  email: andrew@andrewjamesjohnson.com
~/School:
  name: Andrew Johnson
  email: ajohnson478@gatech.edu
~/Dropbox/School:
  name: Andrew Johnson
  email: ajohnson478@gatech.edu