(global-set-key (kbd "RET") 'newline-and-indent)
(global-set-key "\C-x\C-r" 'find-alternative-file-with-sudo)
(global-set-key "\C-x\C-k" 'kill-this-buffer)
(global-set-key "\C-xc" 'delete-frame)
(global-set-key "\C-xv" 'magit-status)
(global-set-key "\C-xf" 'open-current-buffer-in-frame)
(global-set-key "\C-cf" 'indent-region)
(global-set-key "\C-cr" 'replace-string)
(global-set-key "\C-z" 'undo)
(global-set-key "\M-/" 'hippie-expand)
(global-set-key "\M-g" 'goto-line)
(global-set-key [?\C-'] 'other-frame)
(global-set-key "\M-x" 'ido-execute-command)
(global-set-key "\C-cc" 'comment-region)
(global-set-key "\C-cu" 'uncomment-region)
(global-set-key "\M-m" 'move-beginning-of-line)
(global-set-key "\C-a" 'back-to-indentation)
(global-set-key "\C-cw" 'count-words)

(when (eq system-type 'darwin) ;; mac specific settings
  (setq mac-control-modifier 'meta)
  (setq mac-command-modifier 'control))

(provide 'keyboard-shortcuts)
